#!/usr/bin/env python3
"""Discover review-panel models from locally installed agent CLIs.

  review-panel-models.py --list    models each installed CLI offers, recommended first
  review-panel-models.py --init    write the panel config (one family per installed CLI) if absent
  review-panel-models.py --check   report families whose configured model is not the newest
                                   in its line; exit 1 when an update is available

Reads only local CLI state (model caches and config); no network. Config path:
$REVIEW_PANEL_CONF or <house-rules>/custom/review-panel.conf.
"""
import json, os, re, shutil, sys
from pathlib import Path

HOME = Path.home()
CONF = Path(os.environ.get("REVIEW_PANEL_CONF",
            Path(__file__).resolve().parents[3] / "custom" / "review-panel.conf"))
FAMILIES = ["a", "b", "c"]


def version(model):
    """Numeric version tuple and line (model name without the version), for comparison."""
    nums = re.findall(r"\d+(?:\.\d+)*", model)
    ver = tuple(int(p) for p in nums[0].split(".")) if nums else ()
    line = re.sub(r"\d+(?:\.\d+)*", "#", model, count=1)
    return ver, line


def codex_models():
    path = HOME / ".codex" / "models_cache.json"
    if not shutil.which("codex") or not path.exists():
        return []
    models = json.loads(path.read_text()).get("models", [])
    listed = [m for m in models if m.get("visibility") == "list"]
    return [m["slug"] for m in sorted(listed, key=lambda m: m.get("priority", 99))]


def grok_models():
    path = HOME / ".grok" / "models_cache.json"
    if not shutil.which("grok") or not path.exists():
        return []
    found = set(re.findall(r'"(grok-[0-9][0-9a-z.\-]*)"', path.read_text()))
    # Newest version first; within a version prefer the faster-infrastructure variant.
    return sorted(found, key=lambda m: (version(m)[0], m.endswith("-build-fast")), reverse=True)


def kimi_models():
    path = HOME / ".kimi-code" / "config.toml"
    if not shutil.which("kimi") or not path.exists():
        return []
    text = path.read_text()
    default = re.search(r'^default_model\s*=\s*"([^"]+)"', text, re.M)
    names = re.findall(r'^\[models\."([^"]+)"\]', text, re.M)
    first = [default.group(1)] if default else []
    return first + [n for n in names if n not in first]


CLIS = {"codex": codex_models, "grok": grok_models, "kimi": kimi_models}
DEFAULTS = {"codex": "fast high", "grok": "- high", "kimi": ""}


def read_conf():
    conf = {}
    if CONF.exists():
        for line in CONF.read_text().splitlines():
            m = re.match(r"\s*([abc])\s*=\s*(\S+)\s+(\S+)", line)
            if m:
                conf[m.group(1)] = (m.group(2), m.group(3))
    return conf


def newest_in_line(model, available):
    ver, line = version(model)
    same_line = [m for m in available if version(m)[1] == line]
    best = max(same_line, key=lambda m: version(m)[0], default=model)
    return best if version(best)[0] > ver else None


def main(arg):
    available = {cli: fn() for cli, fn in CLIS.items()}
    if arg == "--list":
        for cli, models in available.items():
            print(f"{cli}: {', '.join(models) if models else '(not installed)'}")
        return 0
    if arg == "--init":
        if CONF.exists():
            print(f"exists, not overwritten: {CONF}")
            return 0
        lines = ["# Review panel model families (machine-local). Generated by review-panel-models.py --init."]
        installed = [cli for cli in ("codex", "grok", "kimi") if available[cli]]
        for fam, cli in zip(FAMILIES, installed):
            lines.append(f"{fam} = {cli} {available[cli][0]} {DEFAULTS[cli]}".rstrip())
        CONF.parent.mkdir(parents=True, exist_ok=True)
        CONF.write_text("\n".join(lines) + "\n")
        print("\n".join(lines[1:]) or "no supported CLI installed")
        return 0
    if arg == "--check":
        stale = 0
        for fam, (cli, model) in sorted(read_conf().items()):
            newer = newest_in_line(model, available.get(cli, []))
            if newer:
                stale = 1
                print(f"family {fam}: {cli} offers {newer}, configured {model} — update {CONF}")
        return stale
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else ""))
